services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    env_file:
      - .env.production
    command: redis-server --requirepass ${REDIS_PASSWORD}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.production
